-- Sarojani Funland — Supabase setup
-- Run in: Supabase Dashboard → SQL Editor → New query → paste → Run.
-- Safe to re-run. It never changes or deletes your existing bookings.

-- bookings: matches the table you already have (skipped if it exists)
create table if not exists public.bookings (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  parent_name    text not null,
  child_name     text,
  mobile         text not null,
  activity       text,
  booking_date   text,
  time_slot      text,
  notes          text,
  total_amount   numeric not null default 0,
  children_count integer not null default 1
);

-- enquiries: birthday / group requests from the website form (new table)
create table if not exists public.enquiries (
  id             uuid primary key default gen_random_uuid(),
  created_at     timestamptz not null default now(),
  name           text not null,
  mobile         text not null,
  type           text not null default 'birthday',
  group_size     integer not null default 0,
  preferred_date text,
  message        text
);

-- Security: Row Level Security ON with no policies means the public
-- (publishable) key cannot read or write these tables. The website's server
-- uses the secret key, which bypasses RLS, so bookings keep working.
alter table public.bookings  enable row level security;
alter table public.enquiries enable row level security;

notify pgrst, 'reload schema';
